name: CoverageTests

on: [push, pull_request]

jobs:
  e2e-and-unit:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Compile
        run: yarn compile

      - name: Run unit tests without coverage bc solidity-coverage github authentication issues
        run: yarn test
